services:
  authservice:
    build:
      context: ./CalculX.AuthService
      dockerfile: Dockerfile
    image: calculx-authservice
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - calculx-network

  generalledgerservice:
    build:
      context: ./CalculX.GeneralLedgerService
      dockerfile: Dockerfile
    image: calculx-generalledgerservice
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - calculx-network

networks:
  calculx-network:
    driver: bridge
