services:
  authservice:
    build:
      context: ./CalculX.AuthService
      dockerfile: Dockerfile
    image: calculx-authservice
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - calculx-network

  generalledgerservice:
    build:
      context: ./CalculX.GeneralLedgerService
      dockerfile: Dockerfile
    image: calculx-generalledgerservice
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - calculx-network
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123
    networks:
      - calculx-network
    volumes:
      - sqlserver-data:/var/opt/mssql

networks:
  calculx-network:
    driver: bridge
